<?php //description: Renders the list of public jobs. ?>
<?php
$this->headScript()->appendFile($this->basepath('/Core/js/core.pagination-container.js'))
     ->appendFile($this->basePath('Core/js/core.forms.js'))
     ->appendFile($this->basePath('assets/select2/js/select2.min.js'));
if ($this->params('lang') != 'en') {
    $this->headScript()->appendFile($this->basePath('assets/select2/js/i18n/' . $this->params('lang') . '.js'));
}
$this->headLink()->appendStylesheet($this->basePath('assets/select2/css/select2.css'))
?>
<?php

$queryGet = $this->params()->fromQuery();
unset($queryGet['clear']);
$query= !count($queryGet) ? $this->params()->fromRoute('q', 304) : 0;
$wordpress = $this->proxy('wordpress');

$this->headMeta()->setName('description', $wordpress->chain(['page' => $query, 'value' => 'meta-fields.description'], ''));
$this->headMeta()->setName('keywords', $wordpress->call('value', ['meta-fields.keywords'], ''));
$description = $wordpress->call('value', ['content.rendered'], '');

$title = $wordpress->call('value', ['meta-fields.title'], '');
$this->headTitle($title ?: $this->translate('Jobs'));

$robots = "noindex,follow";
if ($description) { $robots = substr($robots, 2); }
$this->headMeta()->setName('robots', $robots);
$this->headScript()->captureStart();
?>
(function($) {

    $(function() {
        var $tabbar = $('#search-tabs');

        $('#jobs-list-container').on('yk-paginator-container:loaded.jobboard yk-jobs:init', function(ev) {
            $tabbar.show();
            var html = $('#jobs-list-container').find('.pagination-content').html();

            if ('' === html.trim()) { $tabbar.hide(); }
        }).trigger('yk-jobs:init');

        var $jobCount = $('#job-count');

        $('#jobs-list-container').on('yk-paginator-container:loaded.jobboard-job-count', function(ev) {
            var count = $('#update-job-count').text();
            $jobCount.text(count);
        });

        $('#jobs-list-filter').on('reset.jobboard', function(ev) { $(ev.target).find('input.facet-param').remove(); });

    });
})(jQuery);
<?php $this->headScript()->captureEnd();?>

<?php if ($jobs instanceof \Solr\FacetsProviderInterface): $this->headScript()->appendFile($this->basePath('Jobboard/jobs.facets.js')); endif; ?>

<h1 class="text-center">

    <?=$wordpress->call('value', ['title.rendered'], '') ?: 'Aktuelle Stellenanzeigen'; ?>
</h1>

<?php echo $this->flashMessenger()->render('default', array('alert', 'alert-success')) ?>

<nav class="navbar yk-toolbar" id="jobs-list-filter-wrapper">
    <div class="search-form-container">
        <?php
            $queryParams = $this->params()->fromQuery();
            foreach (array_keys($this->jobs->getFacets()->toArray()) as $facetName):
                if (isset($queryParams[$facetName])):
                    foreach (array_keys($queryParams[$facetName]) as $facetValue):
                        $this->filterForm->add(['type' => 'hidden', 'name' => $facetName . '[' . $facetValue . ']',
                                                'attributes' => ['class' => 'facet-param', 'value' => 1]]);
                    endforeach;
                endif;
            endforeach;

            //$this->filterForm->add( ['type' => 'hidden', 'name' => 'clear', 'attributes' => ['value' => 1]]);
            $this->filterForm->setAttribute('data-handle-by', 'native');
            $this->filterForm->setAttribute('action', $this->url('lang/jobboard', [], true));
             echo $this->searchForm($this->filterForm)  ?>
    </div>
</nav>


<ul id="search-tabs" class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#jobs-list-container"><span id="job-count"><?=$this->jobs->getTotalItemCount()?></span> Jobs gefunden</a></li>
    <?php if ($description): ?><li><a data-toggle="tab" href="#wp-content">Beschreibung</a></li><?php endif ?>
</ul>

<div class="tab-content">
    <p></p>
    <div id="jobs-list-container" class="pagination-container tab-pane fade in active"
         data-message="<?php echo $this->escapeHtmlAttr(sprintf(
                                                            $this->translate('%sSorry%s, there are not any jobs matching your search criteria.'),
                                                            '<strong>', '</strong>'
                                                        ))?>"
         data-uri="<?php
         echo $this->url('lang/jobboard', array(), array('query' => $this->params()->fromQuery()), true)?>">

        <div class="pagination-content">
            <?php echo $this->render('jobs/jobboard/index.ajax.phtml')?>
        </div>
    </div>
<?php if ($description):?>
    <div id="wp-content" class="tab-pane fade">
        <?=$description?>
        <?php if (51 == $query): echo $this->landingpages(); endif; ?>
    </div>
<?php endif ?>
</div>
