<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013-2014 Cross Solution (http://cross-solution.de)
 * @author cbleek
 * @license  MIT
 */ ?>

<?php

$this->headTitle('Über das Jobportal');
$this->headscript()->appendScript('$(".alert").alert();');

?>

<h1>Über das Jobboard</h1>

Dieses Jobportal nutzt <a href="http://yawik.org" title="Bewerbermanagement">YAWIK</a> und das
<a href="https://github.com/cbleek/YawikDemoJobboard">YawikDemoJobboard</a>.