<?php
/**
 * YAWIK - Jobboard
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2014 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');
?>
<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang')?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('YAWIK DEMO'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="keywords" value="Open Surce Bewerbermanagement System, Bewerberverwaltung"/>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headScript()
        ->prependFile($this->basepath('Core/js/core.init.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->appendScript('var lang="' . $this->params('lang') . '";'
            . 'var basePath="' . $this->basePath() . '";');
    ?>
    <?php echo $this->headLink() ->prependStylesheet($this->basePath() . '/YawikDemoJobboard/YawikDemoJobboard.css');?>
    <?php echo $this->headStyle() ?>
</head>
<body>
<a class="sr-only" href="#content">Skip to main content</a>
<header id="top" class="navbar navbar-inverse navbar-static-top" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-target=".cam-navbar-collapse" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand hidden-xs" href="<?php echo $this->basepath('/' . $this->params('lang'))?>">YAWIK Jobboard</a>
            <a class="navbar-brand visible-xs" href="<?php echo $this->basepath('/' . $this->params('lang'))?>">Y</a>
        </div>
        <nav id="main-navigation" class="navbar-collapse collapse cam-navbar-collapse" role="navigation">
            <?php
            echo $this->navigation('Core/Navigation')
                ->setAcl($this->services('acl'))
                ->setRole($this->auth('role'))
                ->menu()
                ->setMaxDepth(1)
                ->renderPartial(null, 'main-navigation')?>
            <?php echo $this->loginInfo() ?>
        </nav> <!-- /main-navigation -->
    </div>
</header>
<main id="content" class="col-md-12">
    <?php echo $notifications?>
    <?php echo $this->content; ?>
</main>
<!-- /container -->
<footer id="cam-footer">
    <div class="container">
                <span class="pull-left"><small>&copy; 2013-2014 <a href="http://cross-solution.de">Cross Solution</a>. <?php echo $this->translate('All rights reserved.') ?>
                         </small></span>
                <span class="pull-right"><small>
                        Powered by <a href="http://yawik.org">YAWIK</a>
                    </small> </span>

    </div>
</footer>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
<?php echo $this->partial("piwik")?>
</body>
</html>
